language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
os:
  - linux
if: tag IS blank
install:
  - mvn install -DskipTests=true -B -V
before_deploy:
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER."
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 
    - "target/jDotenv.jar"
    - "target/jDotenv-javadoc.jar"
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    tags: false