language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
os:
  - linux
if: tag IS blank
before_deploy:
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER. Built with oraclejdk8."
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/jDotenv.jar"
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    tags: false